# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 337920);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 6);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140514164129");
user_pref("browser.slowStartup.averageTime", 4882);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20140514164129");
user_pref("browser.startup.homepage_override.mstone", "29.0.1");
user_pref("browser.startup.page", 3);
user_pref("browser.uitour.whitelist.add.260", "");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1402263501323");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1402177101322");
user_pref("datareporting.sessions.current.activeTicks", 13);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 4681);
user_pref("datareporting.sessions.current.main", 2332);
user_pref("datareporting.sessions.current.sessionRestored", 4965);
user_pref("datareporting.sessions.current.startTime", "1402177098069");
user_pref("datareporting.sessions.current.totalTime", 69);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:29.0.1");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1400058969000,\"rdfTime\":1400058898000}}}]");
user_pref("extensions.lastAppVersion", "29.0.1");
user_pref("extensions.lastPlatformVersion", "29.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20140514164129");
user_pref("gecko.mstone", "29.0.1");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 42463);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1402177100);
user_pref("toolkit.telemetry.previousBuildID", "20140514164129");
