[Desktop Entry]
Name=Calen 2.02
Type=X-GNOME-Metatheme
Comment=A theme for Xubuntu, Gtk, and xfwm, based on several other themes i seen in the past.
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Calen-2.00
MetacityTheme=Calen-2.00
IconTheme=black-white_2-Style
GtkColorScheme=fg_color:#d7d7d7,bg_color:#242424,base_color:#474747,text_color:#d7d7d7,selected_bg_color:#d7d7d7,selected_fg_color:#3d3d3d,tooltip_bg_color:#d7d7d7,tooltip_fg_color:#3d3d3d
CursorTheme=default
CursorSize=18
